{-# LANGUAGE NoImplicitPrelude, OverloadedStrings #-}

import WikiPrelude
import Test.HUnit
import Text.MediaWiki.Wiktionary.Base
import Text.MediaWiki.Wiktionary.English

solderEntry :: Text
solderEntry = unlines [
   "==English==",
   "{{slim-wikipedia}}",
   "[[Image:60-40 Solder.jpg|thumb|right|A spool of solder.]]",
   "",
   "===Etymology===",
   "From {{etyl|enm|en}} {{m|enm|solderen}}, from {{etyl|fro|en}} {{m|fro|solder}} (Modern French {{m|fr|souder}}) from {{etyl|la|en}} {{m|la|solidāre}}, present active infinitive of {{m|la|solidō||make solid}}.",
   "",
   "===Pronunciation===",
   "{{der-top|Pronunciation}}",
   "* {{enPR|sŏl'də(r)}}, {{IPA|/ˈsɒldə(ɹ)/|lang=en}}",
   "* {{rhymes|ɒldə(ɹ)|lang=en}}",
   "* {{audio|en-uk-solder.ogg|Audio (UK)|lang=en}}",
   "* {{enPR|sōl'də(r)}}, {{IPA|/ˈsəʊldə(ɹ)/|lang=en}}",
   "* {{rhymes|əʊldə(ɹ)|lang=en}}",
   "* {{audio|en-au-solder.ogg|Audio (AUS)|lang=en}}",
   "* {{audio|en-ca-solder.ogg|Audio (CA)|lang=en}}",
   "* {{a|CanE|GenAm}} {{enPR|sŏd′ər}}, {{IPA|/ˈsɑdɚ/|lang=en}}",
   "* {{rhymes|ɒdə(ɹ)|lang=en}}",
   "* {{audio|en-us-solder.ogg|Audio (US)|lang=en}}",
   "* {{enPR|sōd'ə(r)}}, {{IPA|/ˈsəʊdə(ɹ)/|lang=en}}",
   "* {{rhymes|əʊdə(ɹ)|lang=en}}",
   "{{der-bottom}}",
   "* [http://www.languagehat.com/archives/001382.php LanguageHat discussion on the many pronunciations of “solder”]",
   "",
   "===Noun===",
   "{{en-noun|-}}",
   "",
   "# Any of various [[alloy]]s, often of [[tin]] and [[lead]], that are used to join small pieces of [[metal]] together",
   "",
   "====Translations====",
   "{{trans-top|any of various alloys that are used to join small pieces of metal together}}",
   "* Armenian: {{t+|hy|զոդ}}",
   "* Chinese:",
   "*: Mandarin: {{t+|cmn|焊料|tr=hànliào|sc=Hani}}",
   "* Czech: {{t+|cs|pájka|f}}",
   "* Danish: {{t|da|loddemetal|n}}",
   "* Finnish: {{t|fi|juote}}, {{t|fi|juotosmetalli}}, {{t|fi|juotostina}}",
   "* French: {{t+|fr|soudure|f}}",
   "* German: {{t|de|Lötmetall|n}}, {{t+|de|Lot|n}}, {{t|de|Lötdraht|m}}, {{t+|de|Lötzinn|n}}",
   "* Greek: {{t+|el|συγκολλώ}}",
   "* Icelandic: {{t|is|lóðmálmur|m}}, {{t|is|lóðtin|n}}, {{t|is|brasmálmur|m}}, {{t|is|loðningarefni|n}}",
   "* Japanese: {{t|ja|半田|tr=はんだ, handa|sc=Jpan}}",
   "{{trans-mid}}",
   "* Korean: {{t+|ko|땜납|tr=ddaemnap|sc=Kore}}",
   "* Latvian: {{t|lv|lode|f}}",
   "* Persian: {{t+|fa|لحیم|tr=lahim|sc=fa-Arab}}",
   "* Polish: {{t+|pl|cyna|f}}, {{t|pl|spoiwo lutownicze|n}} {{qualifier|formal}}, {{t+|pl|lut|m}}",
   "* Portuguese: {{t+|pt|solda|f}}",
   "* Russian: {{t+|ru|припо́й|m}}",
   "* Serbo-Croatian: {{t+|sh|lem|m}}",
   "* Spanish: {{t|es|estaño para soldar|m}}, {{t+|es|estaño|m}}",
   "* Turkish: {{t+|tr|lehim}}",
   "* Welsh: {{t+|cy|sodr|m}}",
   "{{trans-bottom}}",
   "",
   "{{checktrans-top}}",
   "* Welsh: {{t-check|cy|sodr}}",
   "{{trans-bottom}}",
   "",
   "===Verb===",
   "{{en-verb}}",
   "",
   "# {{senseid|en|to join with solder}} To join with (or as if with) solder.",
   "",
   "====Antonyms====",
   "* [[desolder]]",
   "",
   "====Derived terms====",
   "* [[solderer]]",
   "* [[soldering iron]]",
   "",
   "====Translations====",
   "{{trans-top|to join with solder}}",
   "* Arabic: {{t-needed|ar}}",
   "* Armenian: {{t+|hy|զոդել}}",
   "* Bulgarian: {{t|bg|запоя́вам|sc=Cyrl}}, {{t+|bg|споя́вам|sc=Cyrl}}",
   "* Chinese:",
   "*: Mandarin: {{t+|cmn|焊接|tr=hànjiē|sc=Hani}}",
   "* Czech: {{t|cs|pájet}}, {{t|cs|letovat}}",
   "* Danish: {{t|da|lodde}}",
   "* Dutch: {{t+|nl|solderen}}",
   "* Esperanto: {{t|eo|luti}}",
   "* Finnish: {{t+|fi|juottaa}}",
   "* French: {{t+|fr|souder}}",
   "* Georgian: {{t-needed|ka}}",
   "* German: {{t+|de|löten}}",
   "* Hebrew: {{t-needed|he}}",
   "* Hindi: {{t-needed|hi}}",
   "* Hungarian: {{t+|hu|forraszt}}",
   "* Icelandic: {{t|is|lóða}}, {{t|is|brasa}}, {{t|is|sjóða saman}}, {{t+|is|kveikja}}, {{t|is|kveikja saman}}",
   "{{trans-mid}}",
   "* Japanese: {{t|ja|はんだづけ|tr=handadzuke suru|alt=はんだづけする|sc=Jpan}}",
   "* Korean: {{t-needed|ko}}",
   "* Latin: {{t+|la|plumbō}}",
   "* Latvian: {{t|lv|lodēt}}",
   "* Macedonian: {{t|mk|леми|tr=lémi}}",
   "* Persian: {{t|fa|لحیم کردن|tr=lahim kardan|sc=fa-Arab}}",
   "* Polish: {{t+|pl|lutować}}",
   "* Portuguese: {{t+|pt|soldar}}",
   "* Quechua: {{t|qu|chapiy}}",
   "* Romanian: {{t-needed|ro}}",
   "* Russian: {{t+|ru|пая́ть|impf}}, {{t+|ru|припая́ть|pf}}, {{t+|ru|спая́ть|pf}}",
   "* Serbo-Croatian: {{t+|sh|zalemiti}}",
   "* Spanish: {{t+|es|soldar}}",
   "* Swedish: {{t+|sv|löda}}",
   "* Thai: {{t-needed|th}}",
   "* Turkish: {{t+|tr|lehimlemek}}",
   "* Vietnamese: {{t+|vi|hàn}}",
   "{{trans-bottom}}",
   "",
   "===See also===",
   "* [[braze]]",
   "* [[flux]]",
   "* [[weld]]",
   "",
   "===Anagrams===",
   "* [[resold#English|resold]]",
   "",
   "[[Category:en:Alloys]]",
   "",
   "----",
   "",
   "==French==",
   "",
   "===Etymology===",
   "Cf. {{m|fr|solde}}.",
   "",
   "===Verb===",
   "{{fr-verb}}",
   "",
   "# to [[close]] (a deal)",
   "# {{label|fr|finance}} to [[settle]], to [[pay off]] (debt)",
   "# to [[sell]] at sales, to have a [[sale]]",
   "# {{label|fr|reflexive|~ '''par'''}} to [[end up]] (in), to [[result]] (in)",
   "",
   "====Conjugation====",
   "{{fr-conj-auto}}",
   "",
   "====Related terms====",
   "* [[solde#French|solde]]",
   "* [[solderie]]",
   "* [[soldeur]]",
   "",
   "===Anagrams===",
   "* [[drôles#French|drôles]]",
   "",
   "===External links===",
   "* {{R:TLFi}}"
   ]

solderFacts :: [WiktionaryFact]
solderFacts = [
    WiktionaryFact "derived/etym" (term ["-","enm"]) (term ["solder","en","","1"]),
    WiktionaryFact "related/etym" (term ["solder","en","","1"]) (term ["solderen","enm"]),
    WiktionaryFact "derived/etym" (term ["-","fro"]) (term ["solder","en","","1"]),
    WiktionaryFact "related/etym" (term ["solder","en","","1"]) (term ["solder","fro"]),
    WiktionaryFact "related/etym" (term ["solder","en","","1"]) (term ["souder","fr"]),
    WiktionaryFact "derived/etym" (term ["-","la"]) (term ["solder","en","","1"]),
    WiktionaryFact "related/etym" (term ["solder","en","","1"]) (term ["solidare","la"]),
    WiktionaryFact "related/etym" (term ["solder","en","","1"]) (term ["solido","la"]),
    WiktionaryFact "definition" (term ["solder","en","Noun","1","def.1"]) (term ["Any of various alloys, often of tin and lead, that are used to join small pieces of metal together","en"]),
    WiktionaryFact "link" (term ["solder","en","Noun","1","def.1"]) (term ["alloy"]),
    WiktionaryFact "link" (term ["solder","en","Noun","1","def.1"]) (term ["tin"]),
    WiktionaryFact "link" (term ["solder","en","Noun","1","def.1"]) (term ["lead"]),
    WiktionaryFact "link" (term ["solder","en","Noun","1","def.1"]) (term ["metal"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["զոդ","hy"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["焊料","cmn"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["pájka","cs"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["loddemetal","da"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["juote","fi"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["juotosmetalli","fi"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["juotostina","fi"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["soudure","fr"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["Lötmetall","de"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["Lot","de"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["Lötdraht","de"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["Lötzinn","de"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["συγκολλω","el"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["lóðmálmur","is"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["lóðtin","is"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["brasmálmur","is"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["loðningarefni","is"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["半田","ja"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["땜납","ko"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["lode","lv"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["لحیم","fa"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["cyna","pl"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["spoiwo lutownicze","pl"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["lut","pl"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["solda","pt"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["припой","ru"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["lem","sh"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["estaño para soldar","es"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["estaño","es"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["lehim","tr"]),
    WiktionaryFact "translation" (term ["solder","en","Noun","1","any of various alloys that are used to join small pieces of metal together"]) (term ["sodr","cy"]),
    WiktionaryFact "definition" (term ["solder","en","Verb","1","to join with solder"]) (term ["To join with (or as if with) solder","en"]),
    WiktionaryFact "antonym" (term ["solder","en","Verb","1"]) (term ["desolder"]),
    WiktionaryFact "derived" (term ["solder","en","Verb","1"]) (term ["solderer"]),
    WiktionaryFact "derived" (term ["solder","en","Verb","1"]) (term ["soldering iron"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["զոդել","hy"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["запоявам","bg"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["споявам","bg"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["焊接","cmn"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["pájet","cs"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["letovat","cs"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["lodde","da"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["solderen","nl"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["luti","eo"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["juottaa","fi"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["souder","fr"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["löten","de"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["forraszt","hu"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["lóða","is"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["brasa","is"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["sjóða saman","is"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["kveikja","is"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["kveikja saman","is"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["はんだづけ","ja"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["plumbo","la"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["lodēt","lv"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["леми","mk"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["لحیم کردن","fa"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["lutować","pl"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["soldar","pt"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["chapiy","qu"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["паять","ru"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["припаять","ru"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["спаять","ru"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["zalemiti","sh"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["soldar","es"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["löda","sv"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["lehimlemek","tr"]),
    WiktionaryFact "translation" (term ["solder","en","Verb","1","to join with solder"]) (term ["hàn","vi"]),
    WiktionaryFact "related" (term ["solder","en","","1"]) (term ["braze"]),
    WiktionaryFact "related" (term ["solder","en","","1"]) (term ["flux"]),
    WiktionaryFact "related" (term ["solder","en","","1"]) (term ["weld"]),
    WiktionaryFact "related/etym" (term ["solder","fr","","1"]) (term ["solde","fr"]),
    WiktionaryFact "definition" (term ["solder","fr","Verb","1","def.1"]) (term ["to close (a deal)","en"]),
    WiktionaryFact "link" (term ["solder","fr","Verb","1","def.1"]) (term ["close"]),
    WiktionaryFact "definition" (term ["solder","fr","Verb","1","def.2"]) (term ["to settle, to pay off (debt)","en"]),
    WiktionaryFact "context" (term ["solder","fr","Verb","1","def.2"]) (term ["finance","en"]),
    WiktionaryFact "link" (term ["solder","fr","Verb","1","def.2"]) (term ["settle"]),
    WiktionaryFact "link" (term ["solder","fr","Verb","1","def.2"]) (term ["pay off"]),
    WiktionaryFact "definition" (term ["solder","fr","Verb","1","def.3"]) (term ["to sell at sales, to have a sale","en"]),
    WiktionaryFact "link" (term ["solder","fr","Verb","1","def.3"]) (term ["sell"]),
    WiktionaryFact "link" (term ["solder","fr","Verb","1","def.3"]) (term ["sale"]),
    WiktionaryFact "definition" (term ["solder","fr","Verb","1","def.4"]) (term ["to end up (in), to result (in)","en"]),
    WiktionaryFact "link" (term ["solder","fr","Verb","1","def.4"]) (term ["end up"]),
    WiktionaryFact "link" (term ["solder","fr","Verb","1","def.4"]) (term ["result"]),
    WiktionaryFact "related" (term ["solder","fr","Verb","1"]) (term ["solde","fr"]),
    WiktionaryFact "related" (term ["solder","fr","Verb","1"]) (term ["solderie"]),
    WiktionaryFact "related" (term ["solder","fr","Verb","1"]) (term ["soldeur"])]



wanjeonEntry :: Text
wanjeonEntry = unlines ["==Korean==",
  "",
  "===Etymology===",
  "{{ko-etym-Sino|完全}}",
  "",
  "===Pronunciation===",
  "{{ko-IPA}}",
  "",
  "===Adverb===",
  "{{ko-adv|hanja=完全}}",
  "",
  "# [[absolutely]], [[completely]], [[totally]]",
  "",
  "===Noun===",
  "{{ko-noun|hanja=完全}}",
  "",
  "# [[perfection]]",
  "",
  "====Derived terms====",
  "* {{ko-l|완전하다}}"]
  
wanjeonFacts :: [WiktionaryFact]
wanjeonFacts = [
  WiktionaryFact "derived/etym" (WiktionaryTerm {wtText="完全", wtSense=Just "sino-korean", wtLanguage=Nothing,wtPos=Nothing,wtEtym=Nothing}) (term ["완전","ko","","1"]) ,
  WiktionaryFact "definition" (term ["완전","ko","Adverb","1","def.1"]) (term ["absolutely","en"]),
  WiktionaryFact "definition" (term ["완전","ko","Adverb","1","def.1"]) (term ["completely","en"]),
  WiktionaryFact "definition" (term ["완전","ko","Adverb","1","def.1"]) (term ["totally","en"]),
  WiktionaryFact "link" (term ["완전","ko","Adverb","1","def.1"]) (term ["absolutely"]),
  WiktionaryFact "link" (term ["완전","ko","Adverb","1","def.1"]) (term ["completely"]),
  WiktionaryFact "link" (term ["완전","ko","Adverb","1","def.1"]) (term ["totally"]),
  WiktionaryFact "definition" (term ["완전","ko","Noun","1","def.1"]) (term ["perfection","en"]),
  WiktionaryFact "link" (term ["완전","ko","Noun","1","def.1"]) (term ["perfection"])
  ]


hadaEntry :: Text
hadaEntry = unlines ["==Korean==",
      "",
      "===Etymology===",
      "{{ko-etym-native|ss|ᄒᆞ다|hota}}",
      "",
      "===Pronunciation===",
      "{{ko-IPA|a=Ko-하다.oga}}",
      "",
      "===Verb===",
      "{{ko-verb}}",
      "",
      "# {{lang|ko|…[[을]] 하다}}",
      "## to [[do]]",
      "##:{{ko-x|[[하루]] [[분]]의 [[일]]을 하다|to '''do''' a full day of [[work]]}}",
      "##:: {{audio|ko|하루 분의 일을 하다.ogg|Audio (South Korea)}}",
      "##:{{ko-x|제가 '''할''' 수 있어요.|I can do it. }}",
      "##:: {{audio|ko|제가 할 수 있어요.ogg|Audio (South Korea)}}",
      "## to [[make]]; to [[arrange]]; to [[cook]]",
      "##:{{ko-x|[[내일]] [[먹다|먹]][[ㄹ|을]] [[밥]]을 [[미리]] 하다|to cook [[rice]] ahead for tomorrow}}",
      "##:: {{audio|ko|내일 먹을 밥을 미리 하다.ogg|Audio (South Korea)}}",
      "## to [[express]] feeling or attitude",
      "##:{{ko-x|[[어둡다|어두]][[ㄴ|운]] [[얼굴]]을 하다|to wear a gloomy face}}",
      "##:: {{audio|ko|어두운 얼굴을 하다.ogg|Audio (South Korea)}}",
      "## to [[take]]; to [[eat]]; to [[drink]]",
      "##:{{ko-x|[[술]]을 [[좀처럼]] '''하지''' 않다|to rarely '''drink''' alcohol}}",
      "##:: {{audio|ko|술을 좀처럼 하지 않다.ogg|Audio (South Korea)}}",
      "## to [[wear]]",
      "##:{{ko-x|[[화려]]한 [[귀걸이]]를 '''하고''' [[나가다]]|to go out '''wearing''' a fancy earring}}",
      "##:: {{audio|ko|화려한 귀걸이를 하고 나가다.ogg|Audio (South Korea)}}",
      "## to [[work]] in/as; to [[operate]]",
      "##:{{ko-x|[[조그맣다|조그만]] [[옷]][[가게]]를 하다|to '''run''' a small clothing store}}",
      "##:: {{audio|ko|조그만 옷가게를 하다.ogg|Audio (South Korea)}}",
      "## to [[play]] a [[role]]; to [[take]] a responsibility for",
      "##:{{ko-x|[[학생]] [[회장]]을 하다|to be the student body president}}",
      "##:: {{audio|ko|학생 회장을 하다.ogg|Audio (South Korea)}}",
      "## to [[get]] a result",
      "##:{{ko-x|[[반]][[에서]] [[일등]]을 하다|to be at top of one's class}}",
      "##:: {{audio|ko|반에서 일등을 하다.ogg|Audio (South Korea)}}",
      "## to [[buy]]; to [[arrange]]",
      "##:{{ko-x|[[휴대폰]]을 [[하나]] 하다|to buy a cell phone}}",
      "##:: {{audio|ko|휴대폰을 하나 하다.ogg|Audio (South Korea)}}",
      "## to [[reach]] a certain price",
      "##:{{ko-x|[[집]] [[한]] [[채]]에 [[십]] [[억]][[이나]] 한다|That house is as much as a billion won.}}",
      "##:: {{audio|ko|집 한 채에 십 억이나 한다.ogg|Audio (South Korea)}}",
      "## (in the form of '…값을 하다') to [[meet]] an expectation",
      "##:{{ko-x|[[밥값]]은 '''해[[어야지|야지]]'''.|I will be worthy of food. (I will work.)}}",
      "## (in the form of 'A B 할 것 없이') to say separately",
      "##:{{ko-x|[[어른]] [[아이]] '''할''' [[것]] [[없다|없]][[이]] [[모두]] [[들뜨다|들떠]] [[있다]].|Everyone is excited regardless of age.}}",
      "# {{lang|ko|…[[을]] —[[게]] 하다}}",
      "## to [[handle]]; to [[dispose]]",
      "##:{{ko-x|이 [[사기범]]을 [[어떻게]] [[ㄹ까|할까]][[요]]?|What to do with this swindler?}}",
      "# {{lang|ko|…[[을]] …[[으로]] 하다}}",
      "## to [[make]] become; to [[cause]] to become",
      "##:{{ko-x|[[여자]]를 [[아내]][[로]] '''하다'''|to '''make''' a woman '''become''' one's wife}}",
      "## to [[head]]; to [[face]]",
      "##:{{ko-x|[[머리]]를 [[북쪽]]으로 '''하고''' [[자다]]|to sleep with the head northward.}}",
      "## to [[decide]]",
      "##:{{ko-x|[[내일]] [[다시]] [[만나다|만나기]]로 하다|to decide to meet again tomorrow}}",
      "# {{lang|ko|…[[을]] —[[고]] 하다}}",
      "## to [[call]]; to [[name]]",
      "##:{{ko-x|[[다르다|다]][[ㄴ|른]] [[말]]과 [[뜻]]이 [[같다|같]][[ㄴ|은]] [[말]]을 '[[동의어]]'[[라고]] 한다.|We call a word which means the same with another word a 'synonym'.}}",
      "# {{lang|ko|…[[으로]] 하다}}",
      "## (in the form of '해서' or '하여') to be [[cause]]d by",
      "##:{{ko-x|이 [[일]]로 하여 그는 [[중징계]]를 [[받다|받]]았다.|Due to this incident, he got heavily disciplined.}}",
      "## (in the form of '해서' or '하여') to go [[via]]",
      "##:{{ko-x|[[부산]]으로 해서 [[일본]]에 [[ㄹ|갈]] [[생각]]이다.|I'm going to visit Japan via Busan.}}",
      "# See below:",
      "## (in the form of '…[[쯤]] 해서') to [[reach]] a certain time",
      "##:{{ko-x|12[[시]] [[반]][[쯤]] 해[[아서|서]] [[가다|갈]][[ㄹ게|게]].|I'll be there around 12:30.}}",
      "## (in the form of '… 하면') to [[make]] something a [[topic]]",
      "##:{{ko-x|[[맥주]] 하[[면]] [[역시]] [[독일]]이다.|To say about beer, Germany is the best.}}",
      "# {{lang|ko|—[[고]] 하다}}",
      "## to [[say]], to [[talk]]",
      "##:{{ko-x|[[잠깐]] [[쉬다|쉬]][[자]][[고]] 하다|to say \"Let's take a rest a bit!\"}}",
      "## (in the form of '하는', often '—고 하는' being shorten to '—하는' or '—는') to be that",
      "##:{{ko-x|[[잠깐]] [[쉬다|쉬]][[자]][[는]] [[소리]]에 나는 그녀를 [[돌아보다|돌아봤]]다.|Hearing a voice saying \"Let's take a rest a bit!\", I looked back to her.}}",
      "# Other uses:",
      "## (after enumerating verbs) to do, actually not doing either of them well",
      "##:{{ko-x|[[앉다|앉]][[았]][[다가]] [[서다|섰]][[다가]] 하다|to alternate between sitting down and standing up}}",
      "## (after an indirect question) to think",
      "##:{{ko-x|그가 [[무얼]] [[보다|보]][[는가]] 했[[더니]] [[만화]][[책]]이었다.|I wondered what he was reading to find it was a comic.}}",
      "## (in the form of '—[[니]] —[[니]] 하다') to say",
      "## (in the form of '—다 하면') to do, emphasizing inevitability",
      "##:{{ko-x|[[쏘다|쐈]]다 하[[면]] [[명중]]이다.|Every time he shoots, it hits the mark.}}",
      "## (after a word descripting sound) to sound",
      "## (after a quotation not followed by any marker) to say",
      "##:{{ko-x|그는 \"[[그만]]!\" 하고 [[외치다|외쳤]]다.|\"Stop!\", he yelled.}}",
      "## (in front of a sentence, in the form of '하나', '하니', '하면', '하여', ' 한데', and '해서') 'but', 'so', 'then', 'thus', 'by the way', and 'therefore' respectively.",
      "# {{lb|ko|auxiliary}}",
      "## (after verb or adjective, in the form of '—게 하다') to make sb/sth do",
      "##:{{ko-x|[[아이]]에게 [[숙제]]를 하게 하다|to have a child do the homework}}",
      "##** cf. {{ko-x|[[아이]]가 [[숙제]]를 한[[ㄴ다|다]].|A child does the homework.}}",
      "##:{{ko-x|[[그릇]]을 [[깨끗하다|깨끗'''하''']]게 하다|to make a dish clean}}",
      "##** cf. {{ko-x|[[그릇]]이 [[깨끗하다|깨끗'''하다''']].|A dish is clean.}}",
      "## (after verb or adjective, in the form of '—었으면 하다') to wish that",
      "##:{{ko-x|나는 [[여름]]에 [[비]]가 [[덜]] [[내리다|내렸]][[으면]] 한[[ㄴ다|다]].|I wish that it rained less in summer.}}",
      "## (after verb or adjective, in the form of '—어야 하다') to have to do",
      "##: {{ko-x|[[모든]] [[재료]]는 [[언제나]] [[신선]]'''해야 한[[ㄴ다|다]]'''.|All ingredients should always be fresh.}}",
      "##: {{ko-x|차를 수리받아야 '''합니다'''.|I need to get my car repaired.}}",
      "##: {{ko-usex|정오 전에 체크아웃 '''해야 합니다'''.|I'll have to check out before noon. }}",
      "## (after verb, in the form of '—으[[려]]([[고]]) 하다' or '—[[고자]] 하다') to intend to",
      "##:{{ko-x|[[이번]] [[주말]]에는 [[영화]]를 [[보다|보]][[려고]] 한[[ㄴ다|다]].|I'm going to watch a movie this weekend.}}",
      "## (in the form of \"verb stem + '—[[기]]' + semantic marker + ' 하다') to do, with an emphasis",
      "##:{{ko-x|그는 [[자다|자]][[기]][[만]] 한[[ㄴ다|다]].|He only sleeps.}}",
      "## (after verb, in the form of '—고 하다') to do, as a cause",
      "##:{{ko-x|[[눈]][[도]] [[오다|오]]고 해[[아서|서]] [[일찍]] [[오다|왔]]다.|'Cause it snows, so I came early.}}",
      "## (after verb, in the form of '—고는 하다' or '—곤 하다') used to do",
      "##:{{ko-x|[[시골]]에 [[살다|살]] [[적]]에, 나는 [[도랑]]을 [[따르다|따라]] [[걷다|걷]]곤 했다.|When I lived in countryside, I used to walk along a ditch.}}",
      "## (after adjective, in the form of '—어하다') to feel that sb/sth is",
      "##:{{ko-x|그는 [[손녀]]를 [[몹시]] [[귀엽다|귀여워]]했다.|He loved his granddaughter very much.}}",
      "",
      "====Usage notes====",
      "{{ko-l|하다}} is a productive suffix for creating verbs and adjectives from Korean nouns. For example,",
      ": {{ko-l|말|word, language}} → {{ko-l|말하다|to talk}}",
      ": {{ko-l|번역|translation}} → {{ko-l|번역하다|to translate}}",
      ": {{ko-l|사랑|love}} → {{ko-l|사랑하다|to love}}",
      "",
      "====Conjugation====",
      "{{ko-conj/verb}}",
      "",
      "====Synonyms====",
      "* {{ko-l|행하다||to do}}",
      "* {{ko-l|삼다|to make; to cause to become}}",
      "* {{ko-l|마시다|to take; to eat; to drink}}",
      "",
      "===Adjective===",
      "{{ko-adj}}",
      "",
      "# (in the form of \"adjective stem + '—기' + semantic marker + ' 하다') to be, with an emphasis",
      "# (after adjective, in the form of '—고 하다') to be, as a cause",
      "",
      "----",
      "",
      "==Middle Korean==",
      "",
      "===Etymology===",
      "{{ko-etym-native|he|하다|hata}} Suspected to have same root with {{ko-l|크다|big}}",
      "",
      "===Adjective===",
      "{{head|okm|adjective|tr=hata}}",
      "",
      "# many; big",
      "#* {{lang|okm|[[w:ko:훈민정음 언해|訓民正音諺解]]本}}",
      "#*: {{ux|okm|[[ᄆᆞᄎᆞᆷ내]] [[제]] [[ᄠᅳᆮ|ᄠᅳ들]] [[시러]] [[펴다|펴]]디 [[몯ᄒㆍ다|몯ᄒᆞᇙ]] [[놈|노미]] '''하니라'''|tr=mochomnay cey ptut-ul sile phyeti mwotholq nwom-i '''hanila'''|...'''many''' of them in the end cannot state their concerns.}}"
      ]

hadaFacts :: [WiktionaryFact]
hadaFacts = [
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1"]) (term ["…을 하다","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.1"]) (term ["to do","en"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.1.1"]) (term ["do"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.1.ex.1"]) (term ["하루 분의 일을 하다","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.1.ex.1.t"]) (term ["to do a full day of work","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.1.ex.1.t"]) (term ["","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.1.ex.2"]) (term ["제가 할 수 있어요.","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.1.ex.2.t"]) (term ["I can do it.","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.1.ex.2.t"]) (term ["","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.2"]) (term ["to make","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.2"]) (term ["to arrange","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.2"]) (term ["to cook","en"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.1.2"]) (term ["make"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.1.2"]) (term ["arrange"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.1.2"]) (term ["cook"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.2.ex.1"]) (term ["내일 먹을 밥을 미리 하다","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.2.ex.1.t"]) (term ["to cook rice ahead for tomorrow","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.2.ex.1.t"]) (term ["","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.3"]) (term ["to express feeling or attitude","en"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.1.3"]) (term ["express"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.3.ex.1"]) (term ["어두운 얼굴을 하다","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.3.ex.1.t"]) (term ["to wear a gloomy face","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.3.ex.1.t"]) (term ["","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.4"]) (term ["to take","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.4"]) (term ["to eat","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.4"]) (term ["to drink","en"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.1.4"]) (term ["take"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.1.4"]) (term ["eat"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.1.4"]) (term ["drink"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.4.ex.1"]) (term ["술을 좀처럼 하지 않다","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.4.ex.1.t"]) (term ["to rarely drink alcohol","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.4.ex.1.t"]) (term ["","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.5"]) (term ["to wear","en"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.1.5"]) (term ["wear"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.5.ex.1"]) (term ["화려한 귀걸이를 하고 나가다","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.5.ex.1.t"]) (term ["to go out wearing a fancy earring","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.5.ex.1.t"]) (term ["","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.6"]) (term ["to work in/as","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.6"]) (term ["to operate","en"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.1.6"]) (term ["work"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.1.6"]) (term ["operate"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.6.ex.1"]) (term ["조그만 옷가게를 하다","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.6.ex.1.t"]) (term ["to run a small clothing store","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.6.ex.1.t"]) (term ["","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.7"]) (term ["to play a role","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.7"]) (term ["to take a responsibility for","en"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.1.7"]) (term ["play"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.1.7"]) (term ["role"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.1.7"]) (term ["take"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.7.ex.1"]) (term ["학생 회장을 하다","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.7.ex.1.t"]) (term ["to be the student body president","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.7.ex.1.t"]) (term ["","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.8"]) (term ["to get a result","en"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.1.8"]) (term ["get"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.8.ex.1"]) (term ["반에서 일등을 하다","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.8.ex.1.t"]) (term ["to be at top of one's class","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.8.ex.1.t"]) (term ["","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.9"]) (term ["to buy","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.9"]) (term ["to arrange","en"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.1.9"]) (term ["buy"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.1.9"]) (term ["arrange"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.9.ex.1"]) (term ["휴대폰을 하나 하다","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.9.ex.1.t"]) (term ["to buy a cell phone","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.9.ex.1.t"]) (term ["","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.10"]) (term ["to reach a certain price","en"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.1.10"]) (term ["reach"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.10.ex.1"]) (term ["집 한 채에 십 억이나 한다","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.10.ex.1.t"]) (term ["That house is as much as a billion won.","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.10.ex.1.t"]) (term ["","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.11"]) (term ["(in the form of '…값을 하다') to meet an expectation","en"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.1.11"]) (term ["meet"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.11.ex.1"]) (term ["밥값은 해야지.","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.11.ex.1.t"]) (term ["I will be worthy of food. (I will work.)","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.12"]) (term ["(in the form of 'A B 할 것 없이') to say separately","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.12.ex.1"]) (term ["어른 아이 할 것 없이 모두 들떠 있다.","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.1.12.ex.1.t"]) (term ["Everyone is excited regardless of age.","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.2"]) (term ["…을 —게 하다","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.2.1"]) (term ["to handle","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.2.1"]) (term ["to dispose","en"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.2.1"]) (term ["handle"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.2.1"]) (term ["dispose"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.2.1.ex.1"]) (term ["이 사기범을 어떻게 할까요?","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.2.1.ex.1.t"]) (term ["What to do with this swindler?","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.3"]) (term ["…을 …으로 하다","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.3.1"]) (term ["to make become","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.3.1"]) (term ["to cause to become","en"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.3.1"]) (term ["make"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.3.1"]) (term ["cause"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.3.1.ex.1"]) (term ["여자를 아내로 하다","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.3.1.ex.1.t"]) (term ["to make a woman become one's wife","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.3.2"]) (term ["to head","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.3.2"]) (term ["to face","en"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.3.2"]) (term ["head"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.3.2"]) (term ["face"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.3.2.ex.1"]) (term ["머리를 북쪽으로 하고 자다","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.3.2.ex.1.t"]) (term ["to sleep with the head northward.","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.3.3"]) (term ["to decide","en"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.3.3"]) (term ["decide"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.3.3.ex.1"]) (term ["내일 다시 만나기로 하다","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.3.3.ex.1.t"]) (term ["to decide to meet again tomorrow","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.4"]) (term ["…을 —고 하다","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.4.1"]) (term ["to call","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.4.1"]) (term ["to name","en"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.4.1"]) (term ["call"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.4.1"]) (term ["name"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.4.1.ex.1"]) (term ["다른 말과 뜻이 같은 말을 '동의어'라고 한다.","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.4.1.ex.1.t"]) (term ["We call a word which means the same with another word a 'synonym'.","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.5"]) (term ["…으로 하다","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.5.1"]) (term ["(in the form of '해서' or '하여') to be caused by","en"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.5.1"]) (term ["cause"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.5.1.ex.1"]) (term ["이 일로 하여 그는 중징계를 받았다.","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.5.1.ex.1.t"]) (term ["Due to this incident, he got heavily disciplined.","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.5.2"]) (term ["(in the form of '해서' or '하여') to go via","en"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.5.2"]) (term ["via"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.5.2.ex.1"]) (term ["부산으로 해서 일본에 갈 생각이다.","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.5.2.ex.1.t"]) (term ["I'm going to visit Japan via Busan.","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.6"]) (term ["See below:","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.6.1"]) (term ["(in the form of '…쯤 해서') to reach a certain time","en"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.6.1"]) (term ["쯤"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.6.1"]) (term ["reach"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.6.1.ex.1"]) (term ["12시 반쯤 해서 갈게.","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.6.1.ex.1.t"]) (term ["I'll be there around 12:30.","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.6.2"]) (term ["(in the form of '… 하면') to make something a topic","en"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.6.2"]) (term ["make"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.6.2"]) (term ["topic"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.6.2.ex.1"]) (term ["맥주 하면 역시 독일이다.","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.6.2.ex.1.t"]) (term ["To say about beer, Germany is the best.","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.7"]) (term ["—고 하다","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.7.1"]) (term ["to say, to talk","en"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.7.1"]) (term ["say"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.7.1"]) (term ["talk"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.7.1.ex.1"]) (term ["잠깐 쉬자고 하다","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.7.1.ex.1.t"]) (term ["to say \"Let's take a rest a bit!\"","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.7.2"]) (term ["(in the form of '하는', often '—고 하는' being shorten to '—하는' or '—는') to be that","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.7.2.ex.1"]) (term ["잠깐 쉬자는 소리에 나는 그녀를 돌아봤다.","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.7.2.ex.1.t"]) (term ["Hearing a voice saying \"Let's take a rest a bit!\", I looked back to her.","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.8"]) (term ["Other uses:","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.8.1"]) (term ["(after enumerating verbs) to do, actually not doing either of them well","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.8.1.ex.1"]) (term ["앉았다가 섰다가 하다","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.8.1.ex.1.t"]) (term ["to alternate between sitting down and standing up","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.8.2"]) (term ["(after an indirect question) to think","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.8.2.ex.1"]) (term ["그가 무얼 보는가 했더니 만화책이었다.","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.8.2.ex.1.t"]) (term ["I wondered what he was reading to find it was a comic.","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.8.3"]) (term ["(in the form of '—니 —니 하다') to say","en"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.8.3"]) (term ["니"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.8.3"]) (term ["니"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.8.4"]) (term ["(in the form of '—다 하면') to do, emphasizing inevitability","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.8.4.ex.1"]) (term ["쐈다 하면 명중이다.","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.8.4.ex.1.t"]) (term ["Every time he shoots, it hits the mark.","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.8.5"]) (term ["(after a word descripting sound) to sound","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.8.6"]) (term ["(after a quotation not followed by any marker) to say","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.8.6.ex.1"]) (term ["그는 \"그만!\" 하고 외쳤다.","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.8.6.ex.1.t"]) (term ["\"Stop!\", he yelled.","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.8.7"]) (term ["(in front of a sentence, in the form of '하나', '하니', '하면', '하여', ' 한데', and '해서') 'but', 'so', 'then', 'thus', 'by the way', and 'therefore' respectively","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.1"]) (term ["(after verb or adjective, in the form of '—게 하다') to make sb/sth do","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.1.ex.1"]) (term ["아이에게 숙제를 하게 하다","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.1.ex.1.t"]) (term ["to have a child do the homework","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.2"]) (term ["(after verb or adjective, in the form of '—었으면 하다') to wish that","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.2.ex.1"]) (term ["나는 여름에 비가 덜 내렸으면 한다.","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.2.ex.1.t"]) (term ["I wish that it rained less in summer.","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.3"]) (term ["(after verb or adjective, in the form of '—어야 하다') to have to do","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.3.ex.1"]) (term ["모든 재료는 언제나 신선해야 한다.","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.3.ex.1.t"]) (term ["All ingredients should always be fresh.","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.3.ex.2"]) (term ["차를 수리받아야 합니다.","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.3.ex.2.t"]) (term ["I need to get my car repaired.","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.3.ex.3"]) (term ["정오 전에 체크아웃 해야 합니다.","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.3.ex.3.t"]) (term ["I'll have to check out before noon.","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.4"]) (term ["(after verb, in the form of '—으려(고) 하다' or '—고자 하다') to intend to","en"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.9.4"]) (term ["려"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.9.4"]) (term ["고"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.9.4"]) (term ["고자"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.4.ex.1"]) (term ["이번 주말에는 영화를 보려고 한다.","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.4.ex.1.t"]) (term ["I'm going to watch a movie this weekend.","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.5"]) (term ["(in the form of \"verb stem + '—기' + semantic marker + ' 하다') to do, with an emphasis","en"]),
      WiktionaryFact "link" (term ["하다","ko","Verb","1","def.9.5"]) (term ["기"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.5.ex.1"]) (term ["그는 자기만 한다.","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.5.ex.1.t"]) (term ["He only sleeps.","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.6"]) (term ["(after verb, in the form of '—고 하다') to do, as a cause","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.6.ex.1"]) (term ["눈도 오고 해서 일찍 왔다.","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.6.ex.1.t"]) (term ["'Cause it snows, so I came early.","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.7"]) (term ["(after verb, in the form of '—고는 하다' or '—곤 하다') used to do","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.7.ex.1"]) (term ["시골에 살 적에, 나는 도랑을 따라 걷곤 했다.","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.7.ex.1.t"]) (term ["When I lived in countryside, I used to walk along a ditch.","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.8"]) (term ["(after adjective, in the form of '—어하다') to feel that sb/sth is","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.8.ex.1"]) (term ["그는 손녀를 몹시 귀여워했다.","ko"]),
      WiktionaryFact "definition" (term ["하다","ko","Verb","1","def.9.8.ex.1.t"]) (term ["He loved his granddaughter very much.","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Adjective","1","def.1"]) (term ["(in the form of \"adjective stem + '—기' + semantic marker + ' 하다') to be, with an emphasis","en"]),
      WiktionaryFact "definition" (term ["하다","ko","Adjective","1","def.2"]) (term ["(after adjective, in the form of '—고 하다') to be, as a cause","en"]),
      WiktionaryFact "definition" (term ["하다","okm","Adjective","1","def.1"]) (term ["many","en"]),
      WiktionaryFact "definition" (term ["하다","okm","Adjective","1","def.1"]) (term ["big","en"])
      ]


testExtract :: (Eq a, Show a) => (Text -> a) -> Text -> a -> Test
testExtract func input output = (cs input) ~: (func input) ~?= output

compareLists :: (Eq a, Show a) => String -> [a] -> [a] -> [Test]
compareLists name input output =
  -- This deliberately runs off the end of the list. If the lists are the
  -- same length, then indexing both of them by (length input) will
  -- confirm this by successfully comparing Nothing to Nothing.
  [(name <> ": item " <> (show i)) ~: (index input i) ~?= (index output i) | i <- [0..(length input)]]

defnTests = [
    -- Parse a definition list with word senses

    testExtract (parseDefinitions "en" enTemplates (termPos "en" "test" "Noun"))
                "# {{senseid|en|first}} definition 1\n# {{senseid|en|second}} definition 2\n# definition 3"
                [WiktionaryFact "definition" (term ["test", "en", "Noun", "", "first"]) (simpleTerm "en" "definition 1"),
                 WiktionaryFact "definition" (term ["test", "en", "Noun", "", "second"]) (simpleTerm "en" "definition 2"),
                 WiktionaryFact "definition" (term ["test", "en", "Noun", "", "def.3"]) (simpleTerm "en" "definition 3")],
                 
    testExtract (parseDefinitions "en" enTemplates (termPos "fr" "test" "Interjection"))
                    "# Definition of bonjour, a French word.\n\
                    \#: Bonjour, les enfants.\n\
                    \#:: Hello, children.\n\
                    \#: Bonjour, comment allez-vous?\n\
                    \#:: Romanization for example (Can be ignored).\n\
                    \#:: Hello, how do you do?\n\
                    \#: {{ux|fr|Un autre exemple.|t=Another example.}}"
                    [WiktionaryFact "definition" (term ["test", "fr", "Interjection", "", "def.1"]) (simpleTerm "en" "Definition of bonjour, a French word"),
                    WiktionaryFact "definition" (term ["test", "fr", "Interjection", "", "def.1.ex.1"]) (simpleTerm "fr" "Bonjour, les enfants."),
                    WiktionaryFact "definition" (term ["test", "fr", "Interjection", "", "def.1.ex.1.t"]) (simpleTerm "en" "Hello, children."),
                    WiktionaryFact "definition" (term ["test", "fr", "Interjection", "", "def.1.ex.2"]) (simpleTerm "fr" "Bonjour, comment allez-vous?"),
                    WiktionaryFact "definition" (term ["test", "fr", "Interjection", "", "def.1.ex.2.t"]) (simpleTerm "en" "Hello, how do you do?"),
                    WiktionaryFact "definition" (term ["test", "fr", "Interjection", "", "def.1.ex.3"]) (simpleTerm "fr" "Un autre exemple."),
                    WiktionaryFact "definition" (term ["test", "fr", "Interjection", "", "def.1.ex.3.t"]) (simpleTerm "en" "Another example.")
                    ],

    testExtract (parseDefinitions "en" enTemplates (termPos "ko" "test" "Determiner"))
                    "# [[new]]\n\
                    \#: '''새''' 집으로 벌써 이사했어요?\n\
                    \#:: '''''Sae''' jip-euro beolsseo isahaess-eoyo?''\n\
                    \#::: Did you already move into your '''new''' house?"
                  [WiktionaryFact "definition" (term ["test","ko", "Determiner", "", "def.1"]) (simpleTerm "en" "new"),
                  WiktionaryFact "link" (term ["test","ko", "Determiner", "", "def.1"]) (term ["new"]),
                  WiktionaryFact "definition" (term ["test","ko", "Determiner", "", "def.1.ex.1"]) (simpleTerm "ko" "새 집으로 벌써 이사했어요?"),
                  WiktionaryFact "definition" (term ["test","ko", "Determiner", "", "def.1.ex.1.t"]) (simpleTerm "en" "Did you already move into your new house?")
                  ],


    -- Parse a "related terms" list, where the first entry has an additional link we ignore
    testExtract (enParseWiktionary always "example")
                "==English==\n===Related terms===\n* [[entry]] with an [[addendum]]\n* [[other]]"
                [WiktionaryFact "related" (term ["example", "en", "", "1"]) (term ["entry"]),
                 WiktionaryFact "related" (term ["example", "en", "", "1"]) (term ["other"])],

    -- Parse a "compound" template two different ways
    testExtract (enParseWiktionary always "placeholder")
                "==English==\n===Etymology===\n{{compound|en|place|holder}}"
                [WiktionaryFact "derived" (term ["place", "en"]) (term ["placeholder", "en", "", "1"]),
                 WiktionaryFact "derived" (term ["holder", "en"]) (term ["placeholder", "en", "", "1"])],

    testExtract (enParseWiktionary always "placeholder")
                "==English==\n===Etymology===\n{{compound|place|holder|lang=en}}"
                [WiktionaryFact "derived" (term ["place", "en"]) (term ["placeholder", "en", "", "1"]),
                 WiktionaryFact "derived" (term ["holder", "en"]) (term ["placeholder", "en", "", "1"])]
    ]

solderTests = compareLists "Example entry for 'solder'" (enParseWiktionary always "solder" solderEntry) solderFacts
wanjeonTests = compareLists "Example entry for '완전'" (enParseWiktionary always "완전" wanjeonEntry) wanjeonFacts
hadaTests = compareLists "Example entry for 'hata'" (enParseWiktionary always "하다" hadaEntry) hadaFacts
tests = test (defnTests ++ solderTests ++ wanjeonTests ++ hadaTests ++ tempText)

main :: IO ()
main = void (runTestTT tests)



always = const . const True


tempText = compareLists "TEMPORARY" (enParseWiktionary always "일월" temp) [] 

temp :: Text
temp = unlines ["==Korean==",
        "",
        "===Pronunciation===",
        "{{ko-IPA}}",
        "",
        "===Etymology 1===",
        "{{ko-etym-Sino|\19968|one|\26376|month}}",
        "",
        "====Alternative forms====",
        "* {{ko-l|1\50900}}",
        "",
        "====Noun====",
        "{{ko-noun|hanja=[[\19968\26376]]\65295[[1\26376]]}}",
        "",
        "# [[January]]",
        "",
        "====See also====",
        "* {{ko-l|\51221\50900||first month of the traditional Korean calendar|\27491\26376}}",
        "",
        "===Etymology 2===",
        "{{ko-etym-Sino|\26085|sun|\26376|moon}}",
        "",
        "===Noun===",
        "{{ko-noun|hanja=\26085\26376}}",
        "",
        "# [[sun]] and [[moon]]",
        "",
        "{{topics|ko|Months}}"]